(()=>{const U=NAH_APP,R=U.$('#app-root');const sops=[
 ['Daily opening','Daily Control',['Review calendar today and tomorrow','Check Trello overdue and due soon','Sort Excel Critical, High, Review','Review rush, Watch List, active/completed alterations, shipments, aging inventory','Prepare Nicole decision list']],
 ['Shipment receiving','Inventory',['Clear receiving rack and preserve packing lists','Open boxes and separate hanging/non-hanging items','Match client, SP, order, COF, garment, quantity','Inspect missing, extra, wrong, or damaged items','Check in when required','Update Trello/Excel and physical location']],
 ['Alteration intake','Alterations',['Verify client, SP, order/COF, exact garment','Record instructions by garment and preserve photos/pins','Choose provider and service type','Record location, client-required date, ETC or follow-up','Create/update Trello and Excel','Do not move unclear garments']],
 ['Factory return','Alterations',['Find correct client/SP and COF','Select Return and exact garment','Check in first if required','Use approved return fields and concise instructions','Print, attach, and stage by destination','Record return number','Verify system receipt next business day']],
 ['Provider follow-up','Alterations',['Confirm provider has exact garment','Ask whether instructions are clear','Ask what is complete and what remains','Obtain a specific ETC','Record response and next follow-up','Escalate client-date risk']],
 ['Completion verification','Alterations',['Treat complete as reported until physical return','Count and identify every piece','Check for incomplete work, damage, or refit','Move to completed scheduling only after verification','Create client-return plan','Review measurement implications']],
 ['WIP / Watch review','Orders',['Print/export current reports','Match by item ID, order, COF, garment','Verify current milestone and exception','Record source, revised date, next follow-up','Escalate client commitments','Correct stale or duplicate records']],
 ['Shipping','Logistics',['Create digital request','Verify address, contents, service, ship-by date','Stage physical garment on shipping rack','Process carrier and record tracking','Monitor through delivery','Close only after confirmed outcome']],
 ['Daily closing','Daily Control',['Document every material contact','Set owner and next date for unresolved items','Reconcile Trello and Excel','Update physical locations','Pack next-day garments','Prepare handoff']]
 ];R.innerHTML=`<div class="app-layout"><div class="stack"><section class="card"><div class="form-grid"><div class="field half"><label>Search procedures</label><input data-search placeholder="factory return, shipping, ETC…"></div><div class="field half"><label>Category</label><select data-category></select></div></div></section><div class="stack" data-list></div></div><aside class="stack app-sidebar"><div class="card"><h3>Abbreviations</h3><div class="queue-list">${[['SP','Sales Professional'],['SA','Sales Assistant'],['OP','Office Professional'],['WIP','Work in Progress'],['COF','Order/customer reference'],['ETC','Expected completion'],['FFBH','Finish functional buttonholes'],['PTP','Point to point'],['HB','Half back'],['HG','Half girth'],['SC','Sport coat'],['CP','Coat and pant'],['AMAP','As much as possible']].map(x=>`<div class="queue-item"><strong>${x[0]}</strong><small>${x[1]}</small></div>`).join('')}</div></div><a class="btn btn-secondary" href="../../resources.html">Configured resources</a></aside></div>`;const cat=U.$('[data-category]');cat.innerHTML='<option value="">All categories</option>'+[...new Set(sops.map(x=>x[1]))].map(x=>`<option>${x}</option>`).join('');function render(){const q=U.$('[data-search]').value.toLowerCase(),c=cat.value,v=sops.filter(x=>(!q||JSON.stringify(x).toLowerCase().includes(q))&&(!c||x[1]===c));U.$('[data-list]').innerHTML=v.map(([title,category,steps])=>`<article class="card"><span class="badge badge-blue">${category}</span><h2 style="margin-top:10px">${title}</h2><ol>${steps.map(x=>`<li>${U.escapeHtml(x)}</li>`).join('')}</ol><button class="btn btn-secondary btn-small" data-copy="${U.escapeHtml(title)}">Copy checklist</button></article>`).join('')||'<div class="empty-state">No procedures match.</div>'}R.addEventListener('click',e=>{const b=e.target.closest('[data-copy]');if(b){const sop=sops.find(x=>x[0]===b.dataset.copy);U.copyText(`${sop[0]}\n${sop[2].map((x,i)=>`${i+1}. ${x}`).join('\n')}`,'Checklist copied')}});U.$('[data-search]').addEventListener('input',render);cat.addEventListener('change',render);render()})();
